#!/bin/bash
#
# Create subdirectories by looking in a fio.job file and formatting the
# name of the subdirectory using the values in the job file.
set -e

if [[ $# -lt 1 ]]; then
  SCRIPT_NAME="$(basename "$0")"
  echo "Usage: $SCRIPT_NAME < workload-size=[large|small] >"
  exit -1
fi
WORKLOAD_SIZE="$1"

read -r -a directories <<< $(ls .)
for directory in "${directories[@]}"; do 
  blocksize=$(sed -e '/^blocksize=/!d' "${directory}/fio.job" | awk -F'=' '{print $2}')
  iodepth=$(sed -e '/^iodepth=/!d' "${directory}/fio.job" | awk -F'=' '{print $2}')
  rwmixwrite=$(sed -e '/^rwmixwrite=/!d' "${directory}/fio.job" | awk -F'=' '{print $2}')
  if [[ -z "$rwmixwrite" ]];then
    rwmixwrite="0"
  fi
  new_directory="${WORKLOAD_SIZE}_workload_${blocksize}_blocksize_${iodepth}_iodepth_${rwmixwrite}_rwmix"
  if [[ ! -d "${new_directory}" ]]; then
    mkdir "${new_directory}" 
  fi
  mv "${directory}" "${new_directory}"
done
